In [45]:
import krippendorff
import numpy as np

In [46]:
import pandas as pd


In [47]:
df = pd.read_excel('tweets_list_modi_jan_5.xlsx')

df

Unnamed: 0                   Datetime             Tweet Id  \
0             0  2022-01-30 18:04:43+00:00  1487849268643729410   
1             1  2022-01-30 13:09:50+00:00  1487775060337512451   
2             2  2022-01-29 17:36:43+00:00  1487479834301272064   
3             3  2022-01-29 08:21:12+00:00  1487340036827885574   
4             4  2022-01-29 03:41:11+00:00  1487269566736596998   
..          ...                        ...                  ...   
770         862  2022-01-30 08:31:13+00:00  1487704943465271296   
771         863  2022-01-30 19:10:57+00:00  1487865939152367617   
772         865  2022-01-30 13:43:38+00:00  1487783566238830594   
773         866  2022-01-30 13:43:04+00:00  1487783424983433220   
774         867  2022-01-30 13:31:58+00:00  1487780630112849931   

                                                  Text         Username  \
0    @Anilthapar123 @Blossom_077 @ArvindKejriwal Ka...      ashutos1794   
1    @AnupamConnects Harami h  . Modi ka kitna chatoge  Adityar64093879   
2    @stomar321 @Hrushikeshrath3 @vikrantsahoo @she...       NarpinderC   
3    @HamidMirPAK @washingtonpost Ye harami asal me...       Mrkhan1822   
4    @stomar321 @Hrushikeshrath3 @vikrantsahoo @she...       NarpinderC   
..                                                 ...              ...   
770  Modi is the most weakest PM of India, now anyo...       india_abby   
771  @avimk001 @PTI_News Abhi bhi tera baap modi Gu...     arsh16081992   
772  @Krishna77579210 Now India is being throttled ...       B2015Malar   
773  @FekuBuster @Ram_Guha Hindus, Christians, Musl...  Annette21908627   
774  @Gen_VKSingh Yahi agar ye Modi ka gun gaan kar...      sandeep_k01   

     Rakshit  Ayan   Shreyas  Category  Category.1  Category.2  Unnamed: 11  \
0          2      2        1       NaN         NaN         NaN          NaN   
1          2      2        1       NaN         NaN         NaN          NaN   
2          2      2        1       NaN         NaN         NaN          NaN   
3          1      1        0       NaN         NaN         NaN          NaN   
4          2      2        1       NaN         NaN         NaN          NaN   
..       ...    ...      ...       ...         ...         ...          ...   
770        1      0        1       NaN         NaN         NaN          NaN   
771        1      1        1       NaN         NaN         NaN          NaN   
772        2      2        2       NaN         NaN         NaN          NaN   
773        2      1        1       NaN         NaN         NaN          NaN   
774        0      0        0       NaN         NaN         NaN          NaN   

     Unnamed: 12  Unnamed: 13  Unnamed: 14 Unnamed: 15  
0            NaN          NaN          NaN         NaN  
1            NaN          NaN          NaN    Category  
2            NaN          0.0        Hate        Caste  
3            NaN          1.0  Instigating    Religion  
4            NaN          2.0        Hate   Individual  
..           ...          ...          ...         ...  
770          NaN          NaN          NaN         NaN  
771          NaN          NaN          NaN         NaN  
772          NaN          NaN          NaN         NaN  
773          NaN          NaN          NaN         NaN  
774          NaN          NaN          NaN         NaN  

[775 rows x 16 columns]

In [48]:
df.columns

Index(['Unnamed: 0', 'Datetime', 'Tweet Id', 'Text', 'Username', 'Rakshit',
       'Ayan ', 'Shreyas', 'Category', 'Category.1', 'Category.2',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15'],
      dtype='object')

In [49]:
df1 = df[['Rakshit',
       'Ayan ', 'Shreyas']]
df1

Rakshit  Ayan   Shreyas
0          2      2        1
1          2      2        1
2          2      2        1
3          1      1        0
4          2      2        1
..       ...    ...      ...
770        1      0        1
771        1      1        1
772        2      2        2
773        2      1        1
774        0      0        0

[775 rows x 3 columns]

In [50]:
value_count = df1.to_numpy()

In [51]:
print(value_count) 

[[2 2 1]
 [2 2 1]
 [2 2 1]
 ...
 [2 2 2]
 [2 1 1]
 [0 0 0]]


In [52]:
b=np.transpose(value_count) 

In [53]:
b

array([[2, 2, 2, ..., 2, 2, 0],
       [2, 2, 2, ..., 2, 1, 0],
       [1, 1, 1, ..., 2, 1, 0]], dtype=int64)

In [54]:

print("Krippendorff's alpha for nominal metric: ", krippendorff.alpha(reliability_data=b,
                                                                      level_of_measurement="nominal"))
print("Krippendorff's alpha for interval metric: ", krippendorff.alpha(reliability_data=b))

Krippendorff's alpha for nominal metric:  0.47384601762670986
Krippendorff's alpha for interval metric:  0.6968456056415663


In [55]:

print("Krippendorff's alpha for ordinal metric: ", krippendorff.alpha(reliability_data=b,
                                                                      level_of_measurement="ordinal"))

Krippendorff's alpha for ordinal metric:  0.6824587516846512
